-- ============================================================
-- FLIGHT DELAY ATTRIBUTION PIPELINE
-- Cross-references airline-reported delay causes against
-- independently-observed weather to detect misattribution.
--
-- Environment: Snowflake (DataExpert shared account)
-- Database:    DATAEXPERT_STUDENT
-- Raw schema:  SAKSHAMPATHAK94148_RAW
-- Mart schema: SAKSHAMPATHAK94148_MARTS
-- ============================================================


-- ============================================================
-- SECTION 1: RAW TABLES
-- Loaded via Snowsight "Create Table from File" wizard:
--   flights_2015_01.csv  -> FLIGHTS_RAW_V2   (469,968 rows)
--   airlines.csv         -> AIRLINES_RAW_V2  (14 rows)
--   airports.csv         -> AIRPORTS_RAW     (322 rows)
--   72219_2015.csv.gz    -> WEATHER_ATL_RAW_2015
--   72259.csv.gz         -> WEATHER_DFW_RAW
--   72295.csv.gz         -> WEATHER_LAX_RAW
--   72530.csv.gz         -> WEATHER_ORD_RAW
--   74486.csv.gz         -> WEATHER_JFK_RAW
-- ============================================================


-- ============================================================
-- SECTION 2: SESSION CONTEXT
-- ============================================================
USE ROLE ALL_USERS_ROLE;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DATAEXPERT_STUDENT;

CREATE SCHEMA IF NOT EXISTS SAKSHAMPATHAK94148_MARTS;
USE SCHEMA SAKSHAMPATHAK94148_MARTS;


-- ============================================================
-- SECTION 3: DIMENSIONS
-- ============================================================

CREATE OR REPLACE TABLE SAKSHAMPATHAK94148_MARTS.DIM_AIRPORT AS
SELECT
    MD5(IATA_CODE) AS AIRPORT_KEY,
    IATA_CODE,
    AIRPORT AS AIRPORT_NAME,
    CITY,
    STATE,
    COUNTRY,
    LATITUDE,
    LONGITUDE
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.AIRPORTS_RAW
WHERE IATA_CODE IS NOT NULL;


CREATE OR REPLACE TABLE SAKSHAMPATHAK94148_MARTS.DIM_CARRIER AS
SELECT
    MD5(C1) AS CARRIER_KEY,
    C1 AS CARRIER_CODE,
    C2 AS CARRIER_NAME
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.AIRLINES_RAW_V2
WHERE C1 IS NOT NULL
  AND C1 != 'IATA_CODE';


-- ============================================================
-- SECTION 4: STAGING
-- ============================================================

CREATE OR REPLACE VIEW SAKSHAMPATHAK94148_MARTS.STG_FLIGHTS AS
SELECT
    MD5(CONCAT_WS('|', YEAR::STRING, MONTH::STRING, DAY::STRING,
                       AIRLINE, FLIGHT_NUMBER::STRING,
                       ORIGIN_AIRPORT, DESTINATION_AIRPORT))  AS FLIGHT_ID,
    DATE_FROM_PARTS(YEAR, MONTH, DAY)                          AS SCHEDULED_DATE,
    UPPER(AIRLINE)                                             AS CARRIER_CODE,
    FLIGHT_NUMBER,
    TAIL_NUMBER,
    UPPER(ORIGIN_AIRPORT)                                      AS ORIGIN_IATA,
    UPPER(DESTINATION_AIRPORT)                                 AS DEST_IATA,
    SCHEDULED_DEPARTURE                                        AS CRS_DEP_TIME_HHMM,
    DEPARTURE_TIME                                             AS ACTUAL_DEP_TIME_HHMM,
    DEPARTURE_DELAY                                            AS DEP_DELAY_MINUTES,
    SCHEDULED_ARRIVAL                                          AS CRS_ARR_TIME_HHMM,
    ARRIVAL_TIME                                               AS ACTUAL_ARR_TIME_HHMM,
    ARRIVAL_DELAY                                              AS ARR_DELAY_MINUTES,
    (CANCELLED = 1)                                            AS IS_CANCELLED,
    CANCELLATION_REASON,
    (DIVERTED = 1)                                             AS IS_DIVERTED,
    DISTANCE                                                   AS DISTANCE_MILES,
    COALESCE(AIRLINE_DELAY, 0)                                 AS CARRIER_DELAY_MINUTES,
    COALESCE(WEATHER_DELAY, 0)                                 AS WEATHER_DELAY_MINUTES,
    COALESCE(AIR_SYSTEM_DELAY, 0)                              AS NAS_DELAY_MINUTES,
    COALESCE(SECURITY_DELAY, 0)                                AS SECURITY_DELAY_MINUTES,
    COALESCE(LATE_AIRCRAFT_DELAY, 0)                           AS LATE_AIRCRAFT_DELAY_MINUTES
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.FLIGHTS_RAW_V2
WHERE YEAR IS NOT NULL;


-- ============================================================
-- SECTION 5: FACT - FLIGHTS
-- ============================================================

CREATE OR REPLACE TABLE SAKSHAMPATHAK94148_MARTS.FCT_FLIGHT AS
SELECT
    f.FLIGHT_ID,
    c.CARRIER_KEY,
    o.AIRPORT_KEY AS ORIGIN_AIRPORT_KEY,
    d.AIRPORT_KEY AS DEST_AIRPORT_KEY,
    f.SCHEDULED_DATE,
    f.FLIGHT_NUMBER,
    f.TAIL_NUMBER,
    f.ORIGIN_IATA,
    f.DEST_IATA,
    f.CRS_DEP_TIME_HHMM,
    f.ACTUAL_DEP_TIME_HHMM,
    f.CRS_ARR_TIME_HHMM,
    f.ACTUAL_ARR_TIME_HHMM,
    f.DEP_DELAY_MINUTES,
    f.ARR_DELAY_MINUTES,
    f.DISTANCE_MILES,
    f.IS_CANCELLED,
    f.IS_DIVERTED,
    f.CANCELLATION_REASON,
    f.CARRIER_DELAY_MINUTES,
    f.WEATHER_DELAY_MINUTES,
    f.NAS_DELAY_MINUTES,
    f.SECURITY_DELAY_MINUTES,
    f.LATE_AIRCRAFT_DELAY_MINUTES,
    (f.ARR_DELAY_MINUTES >= 15)  AS IS_DELAYED_15,
    (f.ARR_DELAY_MINUTES >= 60)  AS IS_DELAYED_60
FROM SAKSHAMPATHAK94148_MARTS.STG_FLIGHTS f
LEFT JOIN SAKSHAMPATHAK94148_MARTS.DIM_CARRIER c ON f.CARRIER_CODE = c.CARRIER_CODE
LEFT JOIN SAKSHAMPATHAK94148_MARTS.DIM_AIRPORT o ON f.ORIGIN_IATA = o.IATA_CODE
LEFT JOIN SAKSHAMPATHAK94148_MARTS.DIM_AIRPORT d ON f.DEST_IATA = d.IATA_CODE;


-- ============================================================
-- SECTION 6: FACT - WEATHER OBSERVATIONS
-- Unions 5 airport weather tables, filtered to January 2015
-- ============================================================

CREATE OR REPLACE TABLE SAKSHAMPATHAK94148_MARTS.FCT_WEATHER_OBSERVATION AS
SELECT 'ATL' AS AIRPORT_IATA, DATE_FROM_PARTS(YEAR, MONTH, DAY) AS OBS_DATE, HOUR AS OBS_HOUR,
    TEMP AS TEMPERATURE_C, RHUM AS RELATIVE_HUMIDITY_PCT, PRCP AS PRECIPITATION_MM,
    WDIR AS WIND_DIRECTION_DEG, WSPD AS WIND_SPEED_KMH, TRY_CAST(WPGT AS NUMBER(38,1)) AS WIND_GUST_KMH,
    PRES AS PRESSURE_HPA, COCO AS WEATHER_CONDITION_CODE
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.WEATHER_ATL_RAW_2015
WHERE YEAR = 2015 AND MONTH = 1

UNION ALL
SELECT 'DFW', DATE_FROM_PARTS(YEAR, MONTH, DAY), HOUR, TEMP, RHUM, PRCP, WDIR, WSPD,
    TRY_CAST(WPGT AS NUMBER(38,1)), PRES, COCO
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.WEATHER_DFW_RAW
WHERE YEAR = 2015 AND MONTH = 1

UNION ALL
SELECT 'LAX', DATE_FROM_PARTS(YEAR, MONTH, DAY), HOUR, TEMP, RHUM, PRCP, WDIR, WSPD,
    TRY_CAST(WPGT AS NUMBER(38,1)), PRES, COCO
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.WEATHER_LAX_RAW
WHERE YEAR = 2015 AND MONTH = 1

UNION ALL
SELECT 'ORD', DATE_FROM_PARTS(YEAR, MONTH, DAY), HOUR, TEMP, RHUM, PRCP, WDIR, WSPD,
    TRY_CAST(WPGT AS NUMBER(38,1)), PRES, COCO
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.WEATHER_ORD_RAW
WHERE YEAR = 2015 AND MONTH = 1

UNION ALL
SELECT 'JFK', DATE_FROM_PARTS(YEAR, MONTH, DAY), HOUR, TEMP, RHUM, PRCP, WDIR, WSPD,
    TRY_CAST(WPGT AS NUMBER(38,1)), PRES, COCO
FROM DATAEXPERT_STUDENT.SAKSHAMPATHAK94148_RAW.WEATHER_JFK_RAW
WHERE YEAR = 2015 AND MONTH = 1;


-- Add adverse-weather flag
CREATE OR REPLACE TABLE SAKSHAMPATHAK94148_MARTS.FCT_WEATHER_OBSERVATION AS
SELECT *,
    CASE WHEN WEATHER_CONDITION_CODE IN (14,15,16,17,18,19,20,21,22,23,24,25,26,27)
              OR WIND_GUST_KMH >= 60
              OR PRECIPITATION_MM >= 5
         THEN TRUE ELSE FALSE END AS IS_ADVERSE_WEATHER
FROM SAKSHAMPATHAK94148_MARTS.FCT_WEATHER_OBSERVATION;


-- ============================================================
-- SECTION 7: MART - FLIGHT + WEATHER
-- The core analytical table. Joins each flight to its origin
-- airport weather at the scheduled departure hour, and flags
-- suspected weather-attribution mismatches.
-- ============================================================

CREATE OR REPLACE TABLE SAKSHAMPATHAK94148_MARTS.MART_FLIGHT_WEATHER AS
SELECT
    f.FLIGHT_ID,
    f.CARRIER_KEY,
    f.ORIGIN_IATA,
    f.DEST_IATA,
    f.SCHEDULED_DATE,
    f.ARR_DELAY_MINUTES,
    f.IS_DELAYED_15,
    f.IS_CANCELLED,
    f.CARRIER_DELAY_MINUTES,
    f.WEATHER_DELAY_MINUTES,
    f.NAS_DELAY_MINUTES,
    f.LATE_AIRCRAFT_DELAY_MINUTES,
    w.TEMPERATURE_C     AS ORIGIN_TEMP_C,
    w.WIND_GUST_KMH     AS ORIGIN_WIND_GUST_KMH,
    w.PRECIPITATION_MM  AS ORIGIN_PRECIP_MM,
    w.IS_ADVERSE_WEATHER AS ORIGIN_ADVERSE_WEATHER,
    CASE WHEN f.IS_DELAYED_15
              AND f.WEATHER_DELAY_MINUTES = 0
              AND w.IS_ADVERSE_WEATHER = TRUE
         THEN TRUE ELSE FALSE END AS IS_WEATHER_ATTRIBUTION_SUSPECT
FROM SAKSHAMPATHAK94148_MARTS.FCT_FLIGHT f
LEFT JOIN SAKSHAMPATHAK94148_MARTS.FCT_WEATHER_OBSERVATION w
    ON f.ORIGIN_IATA = w.AIRPORT_IATA
   AND f.SCHEDULED_DATE = w.OBS_DATE
   AND FLOOR(f.CRS_DEP_TIME_HHMM / 100) = w.OBS_HOUR;


-- ============================================================
-- SECTION 8: ANALYSIS
-- ============================================================

-- 8a. HEADLINE FINDING: % of adverse-weather delays blamed on non-weather causes
-- Result: 111 adverse delays, 95 suspect, 85.6%
SELECT
    SUM(CASE WHEN IS_DELAYED_15 AND ORIGIN_ADVERSE_WEATHER THEN 1 ELSE 0 END) AS total_adverse_delays,
    SUM(CASE WHEN IS_WEATHER_ATTRIBUTION_SUSPECT THEN 1 ELSE 0 END) AS suspect_flights,
    ROUND(100.0 * SUM(CASE WHEN IS_WEATHER_ATTRIBUTION_SUSPECT THEN 1 ELSE 0 END)
          / NULLIF(SUM(CASE WHEN IS_DELAYED_15 AND ORIGIN_ADVERSE_WEATHER THEN 1 ELSE 0 END), 0), 1) AS pct_suspect
FROM SAKSHAMPATHAK94148_MARTS.MART_FLIGHT_WEATHER;


-- 8b. Suspect % by airport
-- Result: JFK 90.0%, DFW 85.0%, ATL 84.5%
SELECT
    ORIGIN_IATA,
    SUM(CASE WHEN IS_DELAYED_15 AND ORIGIN_ADVERSE_WEATHER THEN 1 ELSE 0 END) AS adverse_delays,
    SUM(CASE WHEN IS_WEATHER_ATTRIBUTION_SUSPECT THEN 1 ELSE 0 END) AS suspect,
    ROUND(100.0 * SUM(CASE WHEN IS_WEATHER_ATTRIBUTION_SUSPECT THEN 1 ELSE 0 END)
          / NULLIF(SUM(CASE WHEN IS_DELAYED_15 AND ORIGIN_ADVERSE_WEATHER THEN 1 ELSE 0 END), 0), 1) AS pct_suspect
FROM SAKSHAMPATHAK94148_MARTS.MART_FLIGHT_WEATHER
WHERE ORIGIN_IATA IN ('ATL','JFK','DFW')
GROUP BY ORIGIN_IATA
ORDER BY suspect DESC;


-- 8c. Carrier reliability ranking
SELECT
    c.CARRIER_NAME,
    COUNT(*) AS total_flights,
    SUM(CASE WHEN f.IS_DELAYED_15 THEN 1 ELSE 0 END) AS delayed_flights,
    ROUND(100.0 * SUM(CASE WHEN f.IS_DELAYED_15 THEN 1 ELSE 0 END) / COUNT(*), 1) AS delay_rate_pct
FROM SAKSHAMPATHAK94148_MARTS.MART_FLIGHT_WEATHER f
JOIN SAKSHAMPATHAK94148_MARTS.DIM_CARRIER c ON f.CARRIER_KEY = c.CARRIER_KEY
GROUP BY c.CARRIER_NAME
HAVING COUNT(*) >= 500
ORDER BY delay_rate_pct DESC;


-- 8d. Top suspect flights (case-study examples)
SELECT
    ORIGIN_IATA, SCHEDULED_DATE, ARR_DELAY_MINUTES,
    CARRIER_DELAY_MINUTES, NAS_DELAY_MINUTES, LATE_AIRCRAFT_DELAY_MINUTES,
    ORIGIN_TEMP_C, ORIGIN_WIND_GUST_KMH, ORIGIN_PRECIP_MM
FROM SAKSHAMPATHAK94148_MARTS.MART_FLIGHT_WEATHER
WHERE IS_WEATHER_ATTRIBUTION_SUSPECT = TRUE
ORDER BY ARR_DELAY_MINUTES DESC
LIMIT 15;